[package]
name = "primiti-ve/mtkcommands"
description = "A set of tools for games using the EToH Multi-Tower-Kit V4.\nGo to the GitHub repository for more information. https://github.com/Primiti-ve/MTKCommands"
version = "0.0.3"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Cmdr = "evaera/cmdr@1.12.0"
ByteNet = "elitriare/bytenet-max@0.2.3"
TopbarPlus = "1foreverhd/topbarplus@3.2.5"