name: build

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

env:
    GH_TOKEN: ${{ github.token }}

jobs:
  wally:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: rojo build
        uses: CompeyDev/rojo-build-action@0.1.5
        with:
          output: MTKc
          type: rbxm

      - name: Upload files to a GitHub release
        uses: svenstaro/upload-release-action@2.11.2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: MTKc
          asset_name: MTKc
          tag: ${{ github.ref }}
          overwrite: true
          body: "This is my release text"
