name: build

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

env:
    GH_TOKEN: ${{ github.token }}

jobs:
  wally:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: rojo build
        uses: CompeyDev/rojo-build-action@0.1.5
        with:
          output: model
          type: rbxm
