name: wally

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

env:
    GH_TOKEN: ${{ github.token }}
    WALLY_TOKEN: ${{ secrets.WALLY_TOKEN }}

jobs:
  wally:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup rokit
        uses: CompeyDev/setup-rokit@v0.1.2

      - name: login
        run: wally login --token "${{ env.WALLY_TOKEN }}"

      - name: publish
        run: wally publish
