name: Releases

on:
  workflow_dispatch:

permissions:
  contents: write

env:
  GH_TOKEN: ${{ github.token }}
  WALLY_TOKEN: ${{ secrets.WALLY_TOKEN }}

jobs: 
  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Main
        uses: actions/checkout@v4

      - name: Install RoKit
        uses: CompeyDev/setup-rokit@v0.1.2
        with:
          token: ${{ github.token }}

      - name: Install Dependencies
        run: wally install

      - name: Create Packages Directory
        run: mkdir -p Packages

      - name: Build MTKc.rbxm
        run: rojo build -o MTKc.rbxm default.project.json

      - name: Upload pack.rbxm as build artifact
        uses: actions/upload-artifact@v4
        with: 
          name: MTKc
          path: pack.rbxm

      - name: Get Release from wally.toml
        uses: SebRollen/toml-action@v1.0.0
        id: read_toml
        with: 
          file: 'wally.toml'
          field: 'package.version'

      - name: Publish to Wally
        env: 
          WALLY_TOKEN: ${{ env.WALLY_TOKEN }}
        run: |
          mkdir =p ~/.wally
          printf "[tokens]\n\"https://api.wally.run/\" = \"%s\"" "$WALLY_TOKEN" >> ~/.wally/auth.toml
          wally publish

      - name: Release
        uses: softprops/action-gh-release@v1
        with: 
          name: ${{ steps.read_toml.outputs.value }}
          tag_name: ${{ steps.read_toml.outputs.value }}
          files: pack.rbxm
          draft: true